---
- name: "[{{ current_node }}] Execute command '{{ command_item.name }}' ({{ command_item.description }})"
  vars:
    node_name: "{{ current_node | regex_replace('^node-', '') }}"
  shell: "{{ command_item.cmd | replace('{{ inventory_hostname }}', node_name) }}"
  register: command_output
  ignore_errors: true

- name: "[{{ current_node }}] Save output of '{{ command_item.name }}' to {{ current_node }}/{{ command_item.name }}"
  copy:
    content: "{{ command_output.stdout }}\n"
    dest: "{{ base_dir }}/output/{{ hostvars['localhost']['current_timestamp'] }}/{{ current_node }}/{{ command_item.name }}"
    mode: '0644'
  when: command_output.rc == 0

- name: "[{{ current_node }}] Save error output of '{{ command_item.name }}' to {{ current_node }}/{{ command_item.name }}_error"
  copy:
    content: "Error executing command: {{ command_item.cmd }}\n{{ command_output.stderr if command_output is defined else 'Command failed' }}\n"
    dest: "{{ base_dir }}/output/{{ hostvars['localhost']['current_timestamp'] }}/{{ current_node }}/{{ command_item.name }}_error"
    mode: '0644'
  when: command_output.rc != 0 